import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from "next/router";
import Link from "next/link";

const PageA: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Gimwa-App
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>{router.pathname}</code>
        </p>

        <div className={styles.grid}>
          <Link href="/A">
            <a className={styles.card}>Go to page A</a>
          </Link>
          <Link href="/B">
            <a className={styles.card}>Go to page B</a>
          </Link>
          <Link href="/C">
            <a className={styles.card}>Go to page C</a>
          </Link>
          <Link href="/D">
            <a className={styles.card}>Go to page D</a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default PageA
